FROM nginx:1.27-alpine

WORKDIR /var/www/html

COPY docker/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY public /var/www/html/public

RUN mkdir -p /var/www/html/storage/app/public \
    && ln -sf /var/www/html/storage/app/public /var/www/html/public/storage

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
